package com.ebay.behavior.gds.mdm.signal.service;

import com.ebay.behavior.gds.mdm.common.exception.ExternalCallException;
import com.ebay.behavior.gds.mdm.common.model.external.infohub.User;
import com.ebay.behavior.gds.mdm.common.service.InfohubService;
import com.ebay.behavior.gds.mdm.commonSvc.service.EmailService;
import com.ebay.behavior.gds.mdm.signal.common.model.Plan;
import com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction;
import com.ebay.behavior.gds.mdm.signal.config.GovernanceConfiguration;

import jakarta.mail.MessagingException;
import jakarta.validation.constraints.NotBlank;
import jakarta.ws.rs.ForbiddenException;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Transactional;
import org.thymeleaf.context.Context;
import org.thymeleaf.spring6.SpringTemplateEngine;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;

import static com.ebay.behavior.gds.mdm.common.util.ResourceUtils.csvStringToSet;
import static com.ebay.behavior.gds.mdm.common.util.ResourceUtils.getRequestUser;
import static com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction.APPROVE;
import static com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction.CANCEL;
import static com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction.COMPLETE;
import static com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction.HIDE;
import static com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction.REJECT;
import static com.ebay.behavior.gds.mdm.signal.common.model.PlanUserAction.SUBMIT_FOR_REVIEW;
import static java.util.Locale.US;

@Slf4j
@Service
public class PlanActionService {

    @Autowired
    private OwnershipService ownershipService;

    @Autowired
    private EmailService emailService;

    @Autowired
    private PlanService planService;

    @Autowired
    private SpringTemplateEngine templateEngine;

    @Autowired
    private InfohubService infohubService;

    @Autowired
    private GovernanceConfiguration configuration;

    private static final String TEMPLATE_PATH = "templates/";

    private static final String PAGE_STATUS_MESSAGE_TEMPLATE = "plan_status_change_email_template.html";

    private static final Map<String, Object> TEMPLATE_MODEL = Map.of(
            "subject", "Plan status update.",
            "about", "This is an automated message generated by the Onboarding Portal (GDS Metadata Management) application. Please do not reply.",
            "sender", "Onboarding Portal"
    );

    @Transactional(isolation = Isolation.SERIALIZABLE)
    public Plan complete(long planId) {
        val plan = changeStatus(planId, COMPLETE);
        return planService.update(plan, COMPLETE);
    }

    @Transactional(isolation = Isolation.SERIALIZABLE)
    public Plan hide(long planId) {
        val plan = changeStatus(planId, HIDE);
        return planService.update(plan, HIDE);
    }

    @Transactional(isolation = Isolation.SERIALIZABLE)
    public Plan cancel(long planId) {
        val plan = changeStatus(planId, CANCEL);
        return planService.update(plan, CANCEL);
    }

    @Transactional(isolation = Isolation.SERIALIZABLE)
    public Plan submitForReview(long planId) {
        val status = planService.getById(planId).getStatus();
        val plan = changeStatus(planId, SUBMIT_FOR_REVIEW);
        val message = getMessage(plan, SUBMIT_FOR_REVIEW, status.name());
        val moderatorEmails = csvStringToSet(configuration.getModerators())
                .stream()
                .map(loginName -> infohubService.findUser(loginName, infohubService.readAllUsers()).map(User::email))
                .flatMap(Optional::stream)
                .toArray(String[]::new);
        sendEmail(planId, moderatorEmails, SUBMIT_FOR_REVIEW, message);
        return planService.update(plan, SUBMIT_FOR_REVIEW);
    }

    @Transactional(isolation = Isolation.SERIALIZABLE)
    public Plan approve(long planId) {
        val plan = changeStatus(planId, APPROVE);
        val message = getMessage(plan, APPROVE, null);
        sendEmail(planId, getUserEmails(plan), APPROVE, message);
        return planService.update(plan, APPROVE);
    }

    @Transactional(isolation = Isolation.SERIALIZABLE)
    public Plan reject(long planId, @NotBlank String comment) {
        val plan = changeStatus(planId, REJECT).setComment(comment);
        val message = getMessage(plan, REJECT, comment);
        sendEmail(planId, getUserEmails(plan), REJECT, message);
        return planService.update(plan, REJECT);
    }

    private String getMessage(Plan plan, PlanUserAction action, String additionalText) {
        if (Objects.isNull(additionalText)) {
            return String.format(getTemplate(action), plan.getId(), plan.getName());
        }
        return String.format(getTemplate(action), plan.getId(), plan.getName(), additionalText);
    }

    private void sendEmail(long planId, String[] to, PlanUserAction action, String message) {
        if (to == null || to.length == 0) {
            log.warn(String.format("No recipients found for Plan %d action %s", planId, action.getValue()));
            return;
        }
        try {
            emailService.sendHtmlMessage(to, configuration.getActions().get(action.getValue().toLowerCase(US)).getSubject(), getHtmlMessage(message));
        } catch (MessagingException ex) {
            log.error(String.format("Cannot send email for Plan %d action %s", planId, action.getValue()), ex);
            throw new ExternalCallException(ex);
        }
    }

    public void validateAction(Plan plan, PlanUserAction action) {
        var user = getRequestUser();
        val permissions = ownershipService.getUserPermissions(plan, user);

        if (!permissions.contains(action)) {
            throw new ForbiddenException(String.format("User %s is not allowed to perform action %s on plan %s status %s",
                    user, action, plan.getId(), plan.getStatus()));
        }
    }

    private String getTemplate(PlanUserAction action) {
        try (val reader = new BufferedReader(new InputStreamReader(new ClassPathResource(
                TEMPLATE_PATH + configuration.getActions().get(action.getValue().toLowerCase(US)).getTemplate()).getInputStream()))) {
            return reader.lines().collect(Collectors.joining());
        } catch (IOException e) {
            log.error("Error reading template file:", e);
            throw new IllegalStateException("Error reading template file", e);
        }
    }

    private String getHtmlMessage(String statusMessage) {
        log.info(statusMessage);
        var templateModel = new HashMap<>(TEMPLATE_MODEL);
        templateModel.put("message", statusMessage);

        var thymeleafContext = new Context();
        thymeleafContext.setVariables(templateModel);

        return templateEngine.process(PAGE_STATUS_MESSAGE_TEMPLATE, thymeleafContext);
    }

    private String[] getUserEmails(Plan plan) {
        val owners = plan.getOwnersAsList();
        owners.add(plan.getCreateBy());
        return owners.stream().distinct()
                .map(loginName -> infohubService.findUser(loginName, infohubService.readAllUsers()).map(User::email))
                .flatMap(Optional::stream).toArray(String[]::new);
    }

    private Plan changeStatus(long planId, PlanUserAction action) {
        val plan = planService.getById(planId);
        validateAction(plan, action);
        plan.setStatus(action.getPlanStatus());
        return plan;
    }
}