INSERT INTO soj_platform_tag (soj_name, name, description, data_type, schema_path) VALUES
('app', 'app_id', 'AppId of the mobile app (native and mweb). https://wiki.vip.corp.ebay.com/x/i5OrH', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("app")'),
('bot_provider', 'bot_provider', 'This field is to provide the information helpful for bot detection.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("bot_provider")'),
('botSignature', 'bot_signature_rule', 'Bot detection result, which is the bot flag.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("botSignature")'),
('browser', 'browser', 'browser', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("browser")'),
('browserFamily', 'browser_family', 'browser family', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("browserFamily")'),
('browserVersion', 'browser_version', 'browser version', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("browserVersion")'),
('bu', 'best_guess_user_id', 'Best Guess User. When the user is not logged in, the user\'s Oracle ID can be inferred from a persistent cookie. This is logged as the bu tag.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("bu")'),
('deviceid', 'device_id', 'Device ID - matches Device ID logged on client', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("deviceid")'),
('deviceType', 'device_type', 'desktop, mobile web, webview', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("deviceType")'),
('dm', 'device_model', 'Property to track the model of a mobile device, eg. Apple,', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("dm")'),
('dn', 'device_name', 'The device name, eg. iPhone12_1', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("dn")'),
('dsktop', 'is_desktop', 'Is desktop device or not', 'java.lang.Boolean', 'event.getEventPayload().getEventProperties().get("dsktop")'),
('eactn', 'event_action', 'Pulsar Event Action', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("eactn")'),
('ec', 'experiment_channel', 'Channel for the Qualified Treatments', 'java.lang.Integer', 'event.getEventPayload().getEventProperties().get("ec")'),
('efam', 'event_family', 'Pulsar Event Family', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("efam")'),
('g', 'guid', 'A globally unique identifier for a client. This is called a GUID, and is dropped in a cookie for every pageview on eBay (and some off-eBay).', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("g")'),
('jdg', 'jdg', 'DO NOT DELTE- This tag is used in pathfinder to print debug response', 'java.lang.Boolean', 'event.getEventPayload().getEventProperties().get("jdg")'),
('mobile', 'mobile_useragent', 'Request determining if the useragent is from mobile or not', 'java.lang.Boolean', 'event.getEventPayload().getEventProperties().get("mobile")'),
('mos', 'mobile_os', 'Operating System for the mobile device', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("mos")'),
('osv', 'operating_system_version', 'Operating system version', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("osv")'),
('p', 'page_id', 'The id of a request web page. This is called PageTypeID or PAGE_ID.', 'java.lang.Integer', 'event.getEventPayload().getEventProperties().get("p")'),
('pagename', 'pagename', 'The Page that is being displayed', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("pagename")'),
('res', 'client_resolution', 'Client UI resolution 1024x768.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("res")'),
('schemaversion', 'schemaversion', 'Rheos schema version for subject: behavior.pathfinder.sojevent.schema The version is used for Avro serialization and deserialization.', 'java.lang.Integer', 'event.getEventPayload().getEventProperties().get("schemaversion")'),
('servedTs', 'served_timestamp', 'served timestamp, derived from Soj\'s server tracking events.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("servedTs")'),
('t', 'site_id', 'Site ID that handles the request of the web page.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("t")'),
('tablet', 'is_tablet', 'Is tablet or not.', 'java.lang.Boolean', 'event.getEventPayload().getEventProperties().get("tablet")'),
('uc', 'buyer_country_id', 'Country Id of the buyer browsing the site', 'java.lang.Integer', 'event.getEventPayload().getEventProperties().get("uc")'),
('ul', 'user_preferred_language', 'User Selected Language Preference (Geo Expansion)', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("ul")'),
('viewedTs', 'viewed_timestamp', 'Viewed timestamp, derived from domain client tracking or Surface Tracking view events.', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("viewedTs")'),
('webview', 'is_webview', 'is webview or not.', 'java.lang.Boolean', 'event.getEventPayload().getEventProperties().get("webview")'),
('name', 'name', 'signal name', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("name")'),
('id', 'id', 'signal id', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("id")'),
('model', 'device_model', 'n/a', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("model")'),
('os', 'os', 'n/a', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("os")'),
('url', 'url', 'n/a', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("url")'),
('referrer', 'referrer', 'n/a', 'java.lang.String', 'event.getEventPayload().getEventProperties().get("referrer")');